import type { ConnectedAPI } from '@midnight-ntwrk/dapp-connector-api';
import type { MidnightProviders } from '@midnight-ntwrk/midnight-js-types';
import { INDEXER_HTTP, INDEXER_WS, CONTRACT_PATH, PRIVATE_STATE_PASSWORD } from '../wallet.constants';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { FetchZkConfigProvider } from '@midnight-ntwrk/midnight-js-fetch-zk-config-provider';
import { ZKConfigProvider } from '@midnight-ntwrk/midnight-js-types';
import { dappConnectorProofProvider } from '@midnight-ntwrk/midnight-js-dapp-connector-proof-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { toHex, fromHex } from '@midnight-ntwrk/midnight-js-utils';
import { Transaction, CostModel } from '@midnight-ntwrk/ledger-v8';

export async function buildProviders(
  connectedApi: ConnectedAPI,
  coinPublicKey: string,
  encryptionPublicKey: string,
  contractAddress?: string,
  existingPrivateStateProvider?: any
): Promise<MidnightProviders> {
  const fetchProvider = new FetchZkConfigProvider(
    `${window.location.origin}${CONTRACT_PATH}`,
    fetch.bind(window)
  );
  const zkConfigProvider = new ArtifactValidatingProvider(fetchProvider);

  const privateStateProvider = existingPrivateStateProvider || levelPrivateStateProvider({
    accountId: coinPublicKey,
    privateStoragePasswordProvider: () => PRIVATE_STATE_PASSWORD,
  });

  if (contractAddress) {
    privateStateProvider.setContractAddress(contractAddress);
  }

  return {
    privateStateProvider,
    publicDataProvider: indexerPublicDataProvider(INDEXER_HTTP, INDEXER_WS),
    zkConfigProvider,
    proofProvider: await dappConnectorProofProvider(connectedApi, zkConfigProvider, CostModel.initialCostModel()),
    walletProvider: {
      getCoinPublicKey: () => coinPublicKey,
      getEncryptionPublicKey: () => encryptionPublicKey,
      async balanceTx(tx: any, _ttl?: Date): Promise<any> {
        const serializedTx = toHex(tx.serialize());
        const received = await connectedApi.balanceUnsealedTransaction(serializedTx);
        return Transaction.deserialize('signature', 'proof', 'binding', fromHex(received.tx));
      },
    },
    midnightProvider: {
      async submitTx(tx: any): Promise<string> {
        await connectedApi.submitTransaction(toHex(tx.serialize()));
        const txIdentifiers = (tx as any).identifiers();
        return txIdentifiers?.[0] ?? '';
      },
    },
  };
}

/**
 * Wrapper around FetchZkConfigProvider that detects Vite SPA fallback HTML
 * and throws for missing artifacts. This prevents garbage HTML from being
 * sent to the proof server as "ZK artifact data."
 *
 * When a built-in ledger circuit like "output" is requested, the base provider
 * would otherwise receive index.html (HTTP 200) and pass it through. This
 * wrapper throws instead, letting the caller (wallet or proof server) fall
 * back to its own internal artifact store.
 */
class ArtifactValidatingProvider extends ZKConfigProvider {
  constructor(private base: ZKConfigProvider) {
    super();
  }

  async getProverKey(circuitId: string) {
    const key = await this.base.getProverKey(circuitId);
    this.validate(key as Uint8Array, `${circuitId}.prover`);
    return key;
  }

  async getVerifierKey(circuitId: string) {
    const key = await this.base.getVerifierKey(circuitId);
    this.validate(key as Uint8Array, `${circuitId}.verifier`);
    return key;
  }

  async getZKIR(circuitId: string) {
    const zkir = await this.base.getZKIR(circuitId);
    this.validate(zkir as Uint8Array, `${circuitId}.bzkir`);
    return zkir;
  }

  private validate(data: Uint8Array, name: string) {
    if (data && data.length > 0 && data.length < 5000) {
      const start = new TextDecoder().decode(data.slice(0, 50)).toLowerCase();
      if (start.includes('<!doctype') || start.includes('<html')) {
        throw new Error(
          `Artifact ${name} is HTML (file missing or Vite SPA fallback). ` +
          `Built-in ledger circuits like "output" are not generated by compactc. ` +
          `Ensure the artifact exists or use a provider that has built-in artifacts.`
        );
      }
    }
  }
}
